name: run-tests
on:
  pull_request:
    paths:
      - "contracts/**"
      - "test/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Installing dependencies
        run: npm install --frozen-lockfile
      - name: Running lint
        run: npm run lint
      - name: Running tests
        run: npm test
