name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x.x
      - run: npm install
      - run: npm run test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ROPSTEN_URL: ${{ secrets.PRIVATE_KEY }}
