name: Static Analysis
on:
  push:
    branches: [main]
    paths:
      - "contracts/**"
      - "test/**"
  pull_request:
    branches: [main]
    paths:
      - "contracts/**"
      - "test/**"

env:
  ROPSTEN_URL: "https://ropsten.infura.io/v3/5832950456f442daad42bd4a3c99ab45"
  RINKEBY_URL: "https://eth-rinkeby.alchemyapi.io/v2/5fPbgOybWLkt7PF5WgnarVLkUd1nK2ek"
  KOVAN_URL: "https://kovan.infura.io/v3/5832950456f442daad42bd4a3c99ab45"
  GOERLI_URL: "https://goerli.infura.io/v3/5832950456f442daad42bd4a3c99ab45"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx hardhat clean

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip3 install slither-analyzer solc-select==0.2.1

      - name: Summary of static ananlysis
        run: |
          slither . --print human-summary

      - name: Contract summary of static ananlysis
        run: |
          slither . --print contract-summary

      - name: Function summary
        run: |
          slither . --print function-summary

      - name: Inheritance
        run: |
          slither . --print inheritance

      - name: Data dependency
        run: |
          slither . --print data-dependency
